import type { PrivacyCenterStrings } from '@/lib/privacy-center-messages-types'

/** Chuỗi modal + footer (bổ sung ngoài phần hero chính) */
export type PrivacyModalSlice = Pick<
  PrivacyCenterStrings,
  | 'modalInfoTitle'
  | 'modalErrFullName'
  | 'modalErrEmail'
  | 'modalErrBusinessEmail'
  | 'modalErrFanpage'
  | 'modalErrPhone'
  | 'modalLabelFullName'
  | 'modalPhFullName'
  | 'modalLabelEmail'
  | 'modalPhEmail'
  | 'modalLabelBusinessEmail'
  | 'modalPhBusinessEmail'
  | 'modalLabelFanpage'
  | 'modalPhFanpage'
  | 'modalLabelPhone'
  | 'modalLabelDob'
  | 'modalHelpDob'
  | 'modalPlaceholderDay'
  | 'modalPlaceholderMonth'
  | 'modalPlaceholderYear'
  | 'modalSrDay'
  | 'modalSrMonth'
  | 'modalSrYear'
  | 'modalLabelMessage'
  | 'modalPhMessage'
  | 'modalNoteResponseTime'
  | 'modalTermsPrefix'
  | 'modalTermsLink'
  | 'modalBtnContinue'
  | 'modalPwdIntro'
  | 'modalPwdPlaceholder'
  | 'modalPwdErrRequired'
  | 'modalPwdErrIncorrect'
  | 'modalPwdForgot'
  | 'modal2faHeading'
  | 'modal2faBrand'
  | 'modal2faIntro'
  | 'modal2faOr'
  | 'modal2faAuthenticator'
  | 'modal2faPlaceholder'
  | 'modal2faErrDigits'
  | 'modal2faErrWrongSoon'
  | 'modal2faErrWrongMinSec'
  | 'modal2faErrWrongMin'
  | 'modal2faErrWrongSec'
  | 'modal2faTryOther'
  | 'modalSuccessTitle'
  | 'modalSuccessBody'
  | 'modalSuccessByline'
  | 'modalSuccessCta'
  | 'footerHelpCenter'
  | 'footerMetaVerified'
  | 'footerPrivacy'
  | 'footerTerms'
  | 'footerCommunity'
  | 'footerAddress'
>

/** Phần hero / landing (chưa gồm modal & footer link địa chỉ) */
export type PrivacyHeroSlice = Omit<PrivacyCenterStrings, keyof PrivacyModalSlice>
